### ISSUE TITLE
Missing dependency javax.activation

### ISSUE THREAD

**Issue by benji1000** [mbechler/marshalsec#15]
Hello,

I get the following error when compiling on Kali:

```
[ERROR] /opt/marshalsec/src/main/java/marshalsec/gadgets/JDKUtil.java:[52,24] package javax.activation does not exist
```

Adding the following block to the `<dependencies>` section of the pom.xml file does the trick:

```
<dependency>
    <groupId>javax.activation</groupId>
    <artifactId>activation</artifactId>
    <version>1.1.1</version>
</dependency>
```

Cheers!

**Comment by 0xTen** [comment]
Hi! you need java jdk 8 in order to build... I had the same issue. Still can't make it work properly since java 8 is super old

**Comment by HomeSen** [comment]
Just in case someone else struggles with this: Simply add the following dependency to the `pom.xml`

```
<dependency>
    <groupId>com.sun.activation</groupId>
    <artifactId>javax.activation</artifactId>
    <version>1.2.0</version>
</dependency>
```
