### ISSUE TITLE
snapshot version

### ISSUE THREAD

**Issue by vah13** [mbechler/marshalsec#2]
Hi, do you have compiled version? can you put it to release version, because for compiling need to download more dependencies?

**Comment by mbechler** [comment]
Distributing in binary form unfortunately poses some licensing issues and also may be in conflict with github policy, so I'd rather avoid that if possible.

The only non-runtime dependency I can see is junit, so I don't see that making too much of a difference.

**Comment by vah13** [comment]
ok, tnx
