### ISSUE TITLE
Could not find or load main class

### ISSUE THREAD

**Issue by monixxxx** [mbechler/marshalsec#24]
``root@vmi651682:~/downloads/marshalsec# java -cp target/marshalsec-0.0.1-SNAPSHOT-all.jar marshalsec.jndi.LDAPRefServer "http://127.0.0.1:8885/exp.class"``
``Error: Could not find or load main class marshalsec.jndi.LDAPRefServer``
``Caused by: java.lang.ClassNotFoundException: marshalsec.jndi.LDAPRefServer``
``root@vmi651682:~/downloads/marshalsec#``

**Comment by mbechler** [comment]
The class is definitely there if you build it correctly. Dependency issue?

**Comment by Cyopeng** [comment]
cd into main/java/marshalsec/jndi and rename the class in your command marshalsec.jndi.LDAPRefServer to jndi.LDAPRefServer

**Comment by mbechler** [comment]
That should not be necessary. But on second thought target/marshalsec-0.0.1-SNAPSHOT-all.jar should probably be target/marshalsec-0.0.3-SNAPSHOT-all.jar. Check that the file is actually there.

**Comment by Aholicknight** [comment]
Having the same error

**Comment by Retr02332** [comment]
Having the same error (X2)
