### ISSUE TITLE
Why can't execute commands?

### ISSUE THREAD

**Issue by bsmali4** [mbechler/marshalsec#3]
java -cp marshalsec-0.0.1-SNAPSHOT-all.jar marshalsec.JsonIO -t Groovy whoami

Running gadget Groovy:
Had execution of whoami

**Comment by mbechler** [comment]
Test mode (-t) is running with a SecurityManager that just checks whether a command execution occurs and prevents it. Does that answer your question? Do you have the need for a mode that would execute it?
