### ISSUE TITLE
No connection between Marshalsec and HTTP server

### ISSUE THREAD

**Issue by ghost** [mbechler/marshalsec#32]
When the marshalsec gets the request, it displays the message and should refer the request to the http server. But the http server shows no requests. Am i doing it wrong?? 

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

**Comment by mbechler** [comment]
Maybe #28 has some info
