### ISSUE TITLE
cant build

### ISSUE THREAD

**Issue by radioactivecabinet** [mbechler/marshalsec#33]
ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/home/kali). Please verify you invoked Maven from the correct directory. -> [Help 1]

**Comment by palmero334** [comment]
s

**Comment by benomat** [comment]
I am having the same issue. How did you solve this?

**Comment by mbechler** [comment]
Change into the correct directory.

**Comment by benomat** [comment]
> Change into the correct directory.

What is the correct directory?

**PS: I got it to work. I had to go into the marshalsec directory! :D**
