### ISSUE TITLE
Exception in thread "main" java.lang.IllegalAccessError

### ISSUE THREAD

**Issue by Cqx06177** [mbechler/marshalsec#41]
Exception in thread "main" java.lang.IllegalAccessError

**Comment by ecki** [comment]
What do you think somebody can do with such a report?

please describe your env, what did you do and the full stack trace. Also the error sounds like a prerequisite explained in read me, so check that first.

**Comment by ecki** [comment]
Since the same error is mentioned in the other issue, there Java 17 instead of java 8 (like documented) was used. So I think this issue can be closed.

**Comment by mbechler** [comment]
I think so, too. See  #42.  Thanks for stepping up, Bernd.
