### ISSUE TITLE
manifest missing

### ISSUE THREAD

**Issue by CaledoniaProject** [mbechler/marshalsec#5]
Hi there,

I just did a fresh build with `mvn clean package -DskipTests` (master branch)

And it's missing manifest

```
%> java -jar target/marshalsec-0.0.3-SNAPSHOT-all.jar
no main manifest attribute, in target/marshalsec-0.0.3-SNAPSHOT-all.jar
```

Can you take a look at the pom.xml?

**Comment by mbechler** [comment]
There is no JAR Main-Class. Each of the generators for the different marshallers has it's own main class.  See **https://github.com/mbechler/marshalsec#usage**

**Comment by CaledoniaProject** [comment]
Thanks

**Comment by ghost** [comment]
is it possible to run this in a container?
