### ISSUE TITLE
Question of spirng 3.x SpringAbstractBeanFactoryPointcutAdvisor NPE

### ISSUE THREAD

**Issue by Ramos-dev** [mbechler/marshalsec#8]
I try to use use this marshaller’s hessian Gadget SpringAbstractBeanFactoryPointcutAdvisor in version spring-aop:3.2.7,
 And I met such error while deserialize:

 
![image](https://user-images.githubusercontent.com/30281131/51183546-800abc80-190c-11e9-95a7-c862db4a14ac.png)

Line 83:
 
![image](https://user-images.githubusercontent.com/30281131/51183552-85680700-190c-11e9-97f0-cb2b10fd9226.png)

It looks like that because of  adviceMonitor is transient so it is null, do you have any advice to solve this problems?

**Comment by Ramos-dev** [comment]
@mbechler

**Comment by mbechler** [comment]
There seems to be some variance in that code over versions. In the 3.2.7 version unfortunately there does not seem to be a way around this. The relevant change is https://github.com/spring-projects/spring-framework/commit/5ac5ec10465948d6ce2864c5d94cfcca5af2e574 so the gadget seems to apply to version 5+ only.

**Comment by Ramos-dev** [comment]
thank for your reply, I review https://jira.spring.io/browse/SPR-14324?redirect=false,and confirm SpringAbstractBeanFactoryPointcutAdvisor only support spring-aop 3.2.18, 4.2.9, 4.3.4, 5.0 M3++
