### ISSUE TITLE
XMLDecoder marshaller

### ISSUE THREAD

**Issue by BastienFaure** [mbechler/marshalsec#9]
Hi dude,

Thanks for your amazing work first. I just wondered if you had plans for integrating XMLDecoder marshaller in your tool or you considered it too simple ?

Would you be interested in a pull-request ?

Thanks

**Comment by mbechler** [comment]
Hi,

I didn't add it because both I didn't think that tooling was required and also that it was more of a honorable mention and not really new.

If you want to submit a pull request, sure, go ahead.
